/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddBankCardTemplate: typeof import('./src/components/AddBankCardTemplate.vue')['default']
    AddCategoryTemplate: typeof import('./src/components/AddCategoryTemplate.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    BankCard: typeof import('./src/components/BankCard.vue')['default']
    ContentHeader: typeof import('./src/components/ContentHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElI: typeof import('element-plus/es')['ElI']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTe: typeof import('element-plus/es')['ElTe']
    ElText: typeof import('element-plus/es')['ElText']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HomeCategories: typeof import('./src/components/HomeCategories.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    OrderCard: typeof import('./src/components/OrderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    UpdateOrderModal: typeof import('./src/components/UpdateOrderModal.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
